config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root to: "listings#index"

  resources :listings do
    resources :reviews
    resources :photos
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_many :reviews
  has_many :photos

  validates_presence_of :name
  validates_presence_of :street
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip

  has_attached_file :photo, :default_url => "/images/:style/default.png"
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :listing

  validates_presence_of :photo

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ActionController::Base.helpers.asset_path('default.gif')
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  validates_presence_of :content
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#   after_create :send_signup_confirmation

# private
#   def send_signup_confirmation
#     UserMailer.signup_confirmation(self).deliver
#   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  load_and_authorize_resource param_method: :listing_params

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listing_path(@listing), notice: "Park added!"
    else
      render 'new'
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @reviews = @listing.reviews.order("created_at DESC")
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to listing_path(@listing), notice: "Park updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_path, notice: "Park deleted!"
  end

private
  def listing_params
    params.require(:listing).permit(:name, :description, :street, :city, :state, :zip)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @listing = Listing.find(params[:listing_id])
    @photo = Photo.new
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @photo = @listing.photos.new(photo_params)
    if @photo.save
      respond_to do |format|
        format.html { redirect_to listing_path(@listing) }
        format.js
      end
    else
      render 'error'
    end
  end

private
  def photo_params
    params.require(:photo).permit(:photo, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @listing = Listing.find(params[:listing_id])
    @review = Review.new
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @review = @listing.reviews.new(review_params)
    if @review.save
      respond_to do |format|
        format.html { redirect_to listing_path(@listing) }
        format.js
      end
    else
      render 'new'
    end
  end

private
  def review_params
    params.require(:review).permit(:content).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <%= link_to "Oregon Skateparks", root_path, class: "title" %>

    <div class="accounts">
      <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, class: "login" %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "login"  %>
      <% else %>
          <%= link_to new_user_registration_path, class: "login" do  %>
            <span class="glyphicon glyphicon-globe"></span> Sign Up
          <% end %> | <%= link_to "Login", new_user_session_path, class: "login"  %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html id="<%= params[:controller].parameterize %>_controller">
<head>
  <title>OregonSkateparks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <div>
      <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible center" role="alert">
          <%= flash[:notice] %> <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible center" role="alert">
          <%= flash[:alert] %> <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        </div>
      <% end %>
    </div>

    <%= yield %>

  </div>
</body>
</html>

app/views/listings/_form.html.erb
<%= bootstrap_form_for @listing, html: {class: "form"} do |f| %>
    <%= f.text_field :name %>

    <%= f.text_area :description %>

    <%= f.text_field :street %>

    <%= f.text_field :city %>

    <%= f.text_field :state %>

    <%= f.text_field :zip %>

  <%= f.primary %>
<% end %>

app/views/listings/_listing.html.erb
<div class="row park">
  <div class="col-xs-3">
    <% if listing.photos.empty? %>
      <%= image_tag 'https://s3-us-west-2.amazonaws.com/skateoregon/static/flag.svg', class: "img-responsive" %>
    <% else %>
      <%= image_tag listing.photos.last.photo.url, class: "img-responsive" %>
    <% end %>
  </div>

  <div class="col-xs-9">
    <%= link_to listing_path(listing), class: "park-title" do %>
      <h3><%= listing.name %></h3>
      <p><%= listing.city %>, <%= listing.state %></p>
      <p><%= listing.description %></p>
    <% end %>
  </div>
</div>

app/views/listings/edit.html.erb
<h1>Edit <%= @listing.name %></h1>

<%= render 'form' %>

app/views/listings/index.html.erb
<% if can? :create, @listing %>
  <%= link_to "Add a Park", new_listing_path(@listing), class: "btn btn-danger btn-block add-park" %>
<% end %>

<div class="park-listing">
  <%= render @listings %>
</div>

app/views/listings/new.html.erb
<h1>Add a Skatepark</h1>

<%= render 'form' %>

app/views/listings/show.html.erb
<div class="content-container">
  <div class="primary">
    <h1><%= @listing.name %></h1>
    <p><%= @listing.description %></p>

    <h2>Photos</h2>
    <div class="row photos">
      <%= render @listing.photos %>
    </div>

    <%= link_to new_listing_photo_path(@listing), id: "add-photo", class: "btn btn-primary btn-block", remote: true do %>
      <span class="glyphicon glyphicon-camera"></span>Add a Photo
    <% end %>

    <h2>Reviews</h2>
    <div class="reviews list-group">
      <%= render @reviews %>
    </div>
      <%= link_to new_listing_review_path(@listing), id: "add-review", class: "btn btn-primary btn-block", remote: true do %>
      <span class="glyphicon glyphicon-pencil"></span>Add a Review
    <% end %>
  </div>

  <div class="secondary">
    <div class="address">
      <h2>Address</h2>
      <address>
        <strong><%= @listing.name %></strong><br>
        <%= @listing.street %><br>
        <%= @listing.city %>, <%= @listing.state %><br>
        <%= @listing.zip %><br>
      </address>
    </div>

    <% if can? :create, @listing %>
    <div class="admin">
      <%= link_to "Edit Park", edit_listing_path(@listing), class: "btn btn-info btn-block" %>
      <%= link_to "Delete", listing_path(@listing), data: {confirm: "You sure?", method: "delete"}, class: "btn btn-danger btn-block" %>
    </div>
    <% end %>
  </div>
</div>

app/views/photos/_form.html.erb
<div class="photo-form">
  <%= render 'layouts/errors', object: @photo %>
  <h3>Add a photo of <%= @listing.name %>:</h3>
  <%= bootstrap_form_for [@listing, @photo], html: {:multipart => true, class: "form", id: "new-photo"}, remote: true do |f| %>

    <%= f.file_field :photo %>

    <%= f.text_field :description%>

    <%= f.primary "Add Photo" %>
  <% end %>
</div>

app/views/photos/_photo.html.erb
<div class="col-xs-6">
  <%= link_to photo.photo.url, class: "thumbnail" do %>
    <%= image_tag photo.photo.url %>
  <% end %>
</div>

app/views/photos/create.js.erb
$('.photo-form').remove();
$('#add-photo').show();
$('.photos').prepend('<%= j render(@photo) %>');

app/views/photos/error.js.erb
$('.photo-form').hide().after('<%= j render("form") %>');

app/views/photos/new.js.erb
$('#add-photo').hide().after('<%= j render("form") %>');

app/views/reviews/_form.html.erb
<%= bootstrap_form_for [@listing, @review], html: {class: "form", id: "new-review"}, remote: true do |f| %>
  <%= f.text_field :content, label: "Add your review of #{@listing.name}:" %>
  <%= f.primary %>
<% end %>

app/views/reviews/_review.html.erb
<div class="list-group-item">
  <p class="list-group-item-heading"><%= review.content %></p>
  <p class="list-group-item-text">Posted by <%= User.find(review.user_id).email %> on <%= review.created_at.strftime("%B %-d, %Y") %></p>
</div>

app/views/reviews/create.js.erb
$('#new-review').remove();
$('#add-review').show();
$('.reviews').prepend('<%= j render(@review) %>');

app/views/reviews/new.js.erb
$('#add-review').hide().after('<%= j render("form") %>');